#  step 1
FROM node:latest as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

# step 2
FROM nginx:alpine
COPY --from=node /app/dist/angular14-tailwind-image /usr/share/nginx/html
